# Generated by Django 3.0.1 on 2020-01-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=50, unique=True)),
                ('pname', models.CharField(max_length=50)),
                ('page', models.IntegerField()),
                ('psex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=6)),
                ('paddress', models.CharField(max_length=100)),
                ('pphone', models.CharField(blank=True, max_length=15)),
                ('pcreated_by', models.CharField(max_length=50, null=True)),
                ('pcreated_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.CharField(blank=True, max_length=50, null=True)),
                ('services', models.ManyToManyField(to='services.Services')),
            ],
            options={
                'db_table': 'Patient',
                'ordering': ['-pcreated_at'],
            },
        ),
    ]
