# Generated by Django 3.0.1 on 2020-01-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcode', models.CharField(max_length=50, unique=True)),
                ('dname', models.CharField(max_length=50)),
                ('ddepart', models.CharField(max_length=50)),
                ('dnmc', models.CharField(max_length=50)),
                ('dphone', models.CharField(blank=True, max_length=15)),
                ('demail', models.EmailField(max_length=254)),
                ('dcreated', models.DateTimeField(auto_now_add=True)),
                ('dcreated_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Doctors',
            },
        ),
    ]
