# Generated by Django 3.0.1 on 2020-01-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table='Services',
        ),
    ]
